// Code generated by "stringer -type TokenType ."; DO NOT EDIT.

package tokens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-1]
	_ = x[EOF-2]
	_ = x[ADD-3]
	_ = x[SUB-4]
	_ = x[MUL-5]
	_ = x[DIV-6]
	_ = x[MOD-7]
	_ = x[POW-8]
	_ = x[AND-9]
	_ = x[OR-10]
	_ = x[XOR-11]
	_ = x[NOT-12]
	_ = x[LESS-13]
	_ = x[LESSEQ-14]
	_ = x[GREAT-15]
	_ = x[GREATEQ-16]
	_ = x[EQUAL-17]
	_ = x[DIFF-18]
	_ = x[SIN-19]
	_ = x[COS-20]
	_ = x[TAN-21]
	_ = x[SQRT-22]
	_ = x[FACT-23]
	_ = x[EXP-24]
	_ = x[LOG-25]
	_ = x[CEIL-26]
	_ = x[FLOOR-27]
	_ = x[ABS-28]
	_ = x[MAX-29]
	_ = x[MIN-30]
	_ = x[SIM-31]
	_ = x[SWAP-32]
	_ = x[DUP-33]
	_ = x[DUP2-34]
	_ = x[DUPLICATE-35]
	_ = x[DROP-36]
	_ = x[OVER-37]
	_ = x[ROT-38]
	_ = x[SIZE-39]
	_ = x[IF-40]
	_ = x[FOR-41]
	_ = x[LBRACE-42]
	_ = x[RBRACE-43]
	_ = x[BOOL-44]
	_ = x[INT-45]
	_ = x[FLOAT-46]
}

const _TokenType_name = "INVALIDEOFADDSUBMULDIVMODPOWANDORXORNOTLESSLESSEQGREATGREATEQEQUALDIFFSINCOSTANSQRTFACTEXPLOGCEILFLOORABSMAXMINSIMSWAPDUPDUP2DUPLICATEDROPOVERROTSIZEIFFORLBRACERBRACEBOOLINTFLOAT"

var _TokenType_index = [...]uint8{0, 7, 10, 13, 16, 19, 22, 25, 28, 31, 33, 36, 39, 43, 49, 54, 61, 66, 70, 73, 76, 79, 83, 87, 90, 93, 97, 102, 105, 108, 111, 114, 118, 121, 125, 134, 138, 142, 145, 149, 151, 154, 160, 166, 170, 173, 178}

func (i TokenType) String() string {
	i -= 1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
