// Code generated by "stringer -type TokenType ."; DO NOT EDIT.

package tokens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-1]
	_ = x[ADD-2]
	_ = x[SUB-3]
	_ = x[MUL-4]
	_ = x[DIV-5]
	_ = x[MOD-6]
	_ = x[POW-7]
	_ = x[AND-8]
	_ = x[OR-9]
	_ = x[XOR-10]
	_ = x[NOT-11]
	_ = x[LESS-12]
	_ = x[LESSEQ-13]
	_ = x[GREAT-14]
	_ = x[GREATEQ-15]
	_ = x[EQUAL-16]
	_ = x[DIFF-17]
	_ = x[SIN-18]
	_ = x[COS-19]
	_ = x[TAN-20]
	_ = x[SQRT-21]
	_ = x[FACT-22]
	_ = x[EXP-23]
	_ = x[LOG-24]
	_ = x[CEIL-25]
	_ = x[FLOOR-26]
	_ = x[ABS-27]
	_ = x[MAX-28]
	_ = x[MIN-29]
	_ = x[SIMETRIC-30]
	_ = x[SWAP-31]
	_ = x[DUP-32]
	_ = x[DUP2-33]
	_ = x[DROP-34]
	_ = x[OVER-35]
	_ = x[ROT-36]
	_ = x[IF-37]
	_ = x[FOR-38]
	_ = x[LBRACE-39]
	_ = x[RBRACE-40]
	_ = x[BOOL-41]
	_ = x[INT-42]
	_ = x[FLOAT-43]
}

const _TokenType_name = "INVALIDADDSUBMULDIVMODPOWANDORXORNOTLESSLESSEQGREATGREATEQEQUALDIFFSINCOSTANSQRTFACTEXPLOGCEILFLOORABSMAXMINSIMETRICSWAPDUPDUP2DROPOVERROTIFFORLBRACERBRACEBOOLINTFLOAT"

var _TokenType_index = [...]uint8{0, 7, 10, 13, 16, 19, 22, 25, 28, 30, 33, 36, 40, 46, 51, 58, 63, 67, 70, 73, 76, 80, 84, 87, 90, 94, 99, 102, 105, 108, 116, 120, 123, 127, 131, 135, 138, 140, 143, 149, 155, 159, 162, 167}

func (i TokenType) String() string {
	i -= 1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
